# Just Another Funky Script Configuration

# environment: "development" or "production"
environment  = "development"

[development]
  [development.sheetGlobal]
    site = "0.0.0.0"
    port = "8765"
    path = "/home/epsi/awatch/code-02-enh"
    file = "test-c.xlsx"
  [development.sheetDaily]
    site = "0.0.0.0"
    port = "8767"
    path = "/home/epsi/awatch/code-02-enh"
    file = "test-d.xlsx"

[production]
  [production.sheetGlobal]
    site = "localhost"
    port = "8765"
    path = 'C:\Users\GK 35\Documents'
    file = "global.xlsx"
  [production.sheetDaily]
    site = "localhost"
    port = "8767"
    path = 'C:\Users\GK 35\Documents'
    file = "daily.xlsx"

